using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using System.Web;

namespace Bollard;
public abstract class HtmlTemplate : RazorTemplate {

    // HTML.Raw

    #region Attribute functions called by code generated by the RazorProjectEngine

    StringBuilder? _attributeBuilder = null;
    String? _attributeSuffix = null;
    bool _attributeHasContent = false;

    protected virtual void BeginWriteAttribute(string? name, string? prefix, int prefixOffset, string? suffix, int suffixOffset, int attributeValuesCount) {
        if (_attributeBuilder != null)
            throw new InvalidOperationException("Call to BeginWriteAttribute when attribute writing is already underway.");
        _attributeBuilder = new StringBuilder();
        _attributeHasContent = false;
        if (prefix is not null)
            _attributeBuilder.Append(prefix);
        _attributeSuffix = suffix;
    }

    protected virtual void WriteAttributeValue(string? prefix, int prefixOffset, object? value, int valueOffset, int valueLength, bool isLiteral) {
        if (_attributeBuilder == null)
            throw new InvalidOperationException("WriteAttributeValue without prior BeginWriteAttribute.");

        if (prefix is not null)
            _attributeBuilder.Append(prefix);

        // Treatment of IHtmlContent goes here.

        if (value is null)
            return;

        var strval = value.ToString();
        if (string.IsNullOrEmpty(strval))
            return;

        if (isLiteral)
            _attributeBuilder.Append(strval);
        else
            HtmlHelper.EncodeTo(strval, _attributeBuilder);

        _attributeHasContent = true;
    }

    protected virtual void EndWriteAttribute() {
        if (_attributeBuilder == null)
            throw new InvalidOperationException("EndWriteAttribute without prior BeginWriteAttribute.");

        if (_attributeHasContent) {
            RawOutput.Write(_attributeBuilder);
            RawOutput.Write(_attributeSuffix);
        }
        _attributeBuilder = null;
        _attributeSuffix = null;
        _attributeHasContent = false;
    }

    #endregion Attribute functions called by code generated by the RazorProjectEngine

    #region Body function generated by the RazorProjectEngine

    /// <summary>
    /// Write an object to the output
    /// </summary>
    /// <param name="obj">The object to be written</param>
    /// <exception cref="InvalidOperationException">Not called while during ExecuteAsync</exception>
    protected virtual void Write(object? obj = null) {
        if (obj is null)
            return;

        if (obj is IHtmlString htmlString) {
            RawOutput.Write(htmlString.ToHtmlString());
            return;
        }

        if (obj is IFormattable formattable) {
            HtmlHelper.EncodeTo(formattable.ToString(null, CultureInfo.CurrentCulture), RawOutput);
            return;
        }

        HtmlHelper.EncodeTo(obj.ToString(), RawOutput);
    }


    #endregion Body function generated by the RazorProjectEngine


}
