using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Bollard;

/// <summary>
/// Minimal template that doesn't do any special encoding. Therefore, it has no HTML member (for HTML.Raw())
/// </summary>
/// <remarks>
/// <para>Default is <see cref="HtmlTemplate"/> whcih is a subclass of this one and performs HTML encoding
/// of data.
/// </para>
/// </remarks>
public abstract class RazorTemplate : IAssetBuilder {

    StringBuilder? _output;
    TextWriter? _outputWriter;

    #region Public Interface
    public void Produce() {
        var oldCultureInfo = CultureInfo.CurrentCulture;
        // TODO: CultureInfo.CurrentCulture = Site/Project.Culture

        _output = new StringBuilder();
        _outputWriter = new StringWriter(_output, CultureInfo.CurrentCulture); // TODO: Change to Site/Project.Culture
        ExecuteAsync().GetAwaiter().GetResult(); // Execute synchroniously.

        // TODO: Handle layouts

        // Restore culture
        CultureInfo.CurrentCulture = oldCultureInfo;
    }

    public void Deliver(Stream stream) {
        _output?.WriteUtf8(stream);
    }

    #endregion Public Interface

    #region Razor Template Entry Point

    /// <summary>
    /// Entry point for the complied Razor code
    /// </summary>
    /// <returns>A task. This is async.</returns>
    /// <remarks>
    /// <para>Must remain abstract. The Razor compiler implements this method.
    /// </para
    /// <para>External callers should not invoke this method. The proper method
    /// to invoke in order to build the template is <see cref="IAssetBuilder.ProduceAsync"/>.
    /// </para>
    /// </remarks>
    public abstract Task ExecuteAsync();

    #endregion Razor Template Entry Point

    #region Available to Razor Templates

    public string? Path { get; set; } = null;

    protected string? Layout { get; set; } = null;

    protected TextWriter RawOutput {
        get {
            if (_outputWriter is null)
                ThrowRazorRuntimeException("WriteRaw is only to be called from the Razor template.");
            return _outputWriter;
        }
    }

    /*
    protected void WriteRaw(object value, string? format = null, CultureInfo? culture = null) {
        if (_output is null)
            ThrowRazorRuntimeException("WriteRaw is only to be called from the Razor template.");

        if (value is null)
            return; // Do nothing

        culture ??= CultureInfo.CurrentCulture;

        if (value is IFormattable formattable) {
            _output.Append(formattable.ToString(format, culture));
            return;
        }

        _output.Append(value.ToString());
    }
    */

    #endregion Available to Razor Templates

    #region Overridden by Razor

    protected virtual string SourceName => "(unknown source)";

    #endregion

    #region Called by code generated by the RazorProjectEngine

    protected virtual void WriteLiteral(string? literal = null) {
        if (_output is null)
            ThrowRazorRuntimeException("WriteLiteral is only to be called from the Razor template.");
        if (string.IsNullOrEmpty(literal))
            return;
        _output.Append(literal);
    }

    /// <summary>
    /// Write an object to the output
    /// </summary>
    /// <param name="obj">The object to be written</param>
    /// <exception cref="InvalidOperationException">Not called while during ExecuteAsync</exception>
    /// <remarks>
    /// This SHOULD be overridden by a method that encodes values in format-specific classes like <see cref="HtmlTemplate"/>.
    /// </remarks>
    protected virtual void Write(object? obj = null) {
        if (_output is null)
            throw new InvalidOperationException("Write is only to be called from the Razor template.");
        if (obj is null)
            return;

        if (obj is IFormattable formattable) {
            _output.Append(formattable.ToString(null, CultureInfo.CurrentCulture));
            return;
        }
        _output.Append(obj.ToString());
    }

    /*
     * When Razor is complied with ParseHtml = true then it can call these additional functions.
     * They are not implemented in RazorTemplate because this class and any derived classes are
     * intended to be used when ParseHtml = false. A future enhancement will be to check for
     * absense of these functions when ParseHtml = true and report a useful error message.

    void BeginWriteAttribute(string name, string prefix, int prefixOffset, string suffix, int suffixOffset, int attributeValuesCount);

    void WriteAttributeValue(string prefix, int prefixOffset, object value, int valueOffset, int valueLength, bool isLiteral);

    void EndWriteAttribute();

     *
     */


    #endregion Called by code generated by the RazorProjectEngine

    #region Internal Help

    [DoesNotReturn]
    protected void ThrowRazorRuntimeException(string message) {
        throw new RazorRuntimeException(message, SourceName);
    }

    #endregion Internal Help
}
