#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\ErrorPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "06816d063964a4b7babafad11ac941a7949353de"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(BollardPages.ErrorPage), @"default", @"/ErrorPage.cshtml")]
namespace BollardPages
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"06816d063964a4b7babafad11ac941a7949353de", @"/ErrorPage.cshtml")]
    public class ErrorPage
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<!-- This page includes invalid Razor syntax. It should generate errors and not be compiled into the assembly. -->\r\n");
            WriteLiteral("invalid\r\nSomething\r\nSomething else\r\n");
#nullable restore
#line 5 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\ErrorPage.cshtml"
         
// Block left open.

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
