#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\NamespacePage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6365bad95da89e8b76b85d909f3d2926a8e0a97b"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Phred.NamespacePage), @"default", @"/NamespacePage.cshtml")]
namespace Phred
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"6365bad95da89e8b76b85d909f3d2926a8e0a97b", @"/NamespacePage.cshtml")]
    public class NamespacePage
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<html>\r\n<body>\r\n    <h1>Namespaced</h1>\r\n</body>\r\n</html>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
