#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\TestPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "b65b7b97e980f2eb25cf17777bc699f8581b0ec4"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(HooDoo.Template), @"default", @"/TestPage.cshtml")]
namespace HooDoo
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"b65b7b97e980f2eb25cf17777bc699f8581b0ec4", @"/TestPage.cshtml")]
    public class Template : RazorTemplate
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<html>\r\n<head>\r\n    <title>Test Page</title>\r\n</head>\r\n<body>\r\n    <h1>Test Page</h1>\r\n    <p>Hello, world!</p>\r\n    <p>");
#nullable restore
#line 10 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\TestPage.cshtml"
  Write(DateTime.Now);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n</body>\r\n</html>\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
