#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\TestPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "bc911c645d0436e8ee98bebc8cac4cdb95c82fc4"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(HooDoo.Template), @"default", @"/TestPage.cshtml")]
namespace HooDoo
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"bc911c645d0436e8ee98bebc8cac4cdb95c82fc4", @"/TestPage.cshtml")]
    public class Template : RazorTemplate
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\TestPage.cshtml"
Write(page);

#line default
#line hidden
#nullable disable
            WriteLiteral(" Hello\r\n<html>\r\n<head>\r\n    <title>Test Page</title>\r\n</head>\r\n<body>\r\n    <h1>Test Page</h1>\r\n    <p>Hello, world!</p>\r\n    <p>");
#nullable restore
#line 9 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\TestPage.cshtml"
  Write(DateTime.Now);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n</body>\r\n</html>\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
