#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\TestPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0166de70384e53de02938fcbe27ac91c87b2afcd"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(HooDoo.Template), @"default", @"/TestPage.cshtml")]
namespace HooDoo
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"0166de70384e53de02938fcbe27ac91c87b2afcd", @"/TestPage.cshtml")]
    public class Template : RazorTemplate
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            Layout = "Phred";
            WriteLiteral("<html>\r\n<head>\r\n    <title>Test Page</title>\r\n</head>\r\n<body>\r\n    <h1>Test Page</h1>\r\n    <p>Hello, world!</p>\r\n    <p>");
#nullable restore
#line 10 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\TestPage.cshtml"
  Write(DateTime.Now);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n</body>\r\n</html>\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
