#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\WarningPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "23793030dbc95782a548449efc9039911c34aa80"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(HooDoo.Template), @"default", @"/WarningPage.cshtml")]
namespace HooDoo
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"23793030dbc95782a548449efc9039911c34aa80", @"/WarningPage.cshtml")]
    public class Template : RazorTemplate
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 2 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\WarningPage.cshtml"
  
#warning This warning comes in the second pass when the c# is compiled. 

#line default
#line hidden
#nullable disable
            WriteLiteral("<html>\r\n<body>\r\n    <p>This page generates a warning.</p>\r\n    ");
#nullable restore
#line 8 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\WarningPage.cshtml"
Write(undefined);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</body>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
