#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\WarningPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3c252ef83e206e85da173c22d17947837d4f72a4"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(BBollard.WarningPage), @"default", @"/WarningPage.cshtml")]
namespace BBollard
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"3c252ef83e206e85da173c22d17947837d4f72a4", @"/WarningPage.cshtml")]
    public class WarningPage
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\"Something.Else\"\r\n");
#nullable restore
#line 3 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\WarningPage.cshtml"
  
#warning This warning comes in the second pass when the c# is compiled. 

#line default
#line hidden
#nullable disable
            WriteLiteral("<html>\r\n<body>\r\n    <p>This page generates a warning.</p>\r\n    ");
#nullable restore
#line 9 "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\WarningPage.cshtml"
Write(undefined);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</body>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
