#pragma checksum "C:\Users\brand\Source\bredd\Bollard\Tests\NewArchitecture\Sub\SubPage.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2cf41930dfcfcbd648a0e84e171f639b364770c2"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(BBollard.Sub.SubPage), @"default", @"/Sub/SubPage.cshtml")]
namespace BBollard.Sub
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2cf41930dfcfcbd648a0e84e171f639b364770c2", @"/Sub/SubPage.cshtml")]
    public class SubPage
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<html>\r\n<body>\r\n    <h1>SubPage</h1>\r\n</body>\r\n</html>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
